/* PulseFit v2: shared components, route-preserving presentation, localisation and motion. */
const legacyScreens={...screens},legacyRender=render,legacyGo=go,legacyNav=nav,legacyBack=backNow,legacyAfter=afterRender;
const orb='assets/ai-orb.webp',yogaPhoto='assets/community-yoga.webp',foodPhoto='assets/food-bowl.webp';
const nf=(n,opts={})=>PF_I18N.number(n,state.lang,opts), df=(d='2026-09-18T12:00:00',opts)=>PF_I18N.date(d,state.lang,opts);
const score=()=>82+Math.min(state.workouts.length*2,16), workoutMinutes=()=>state.workouts.reduce((a,b)=>a+b.minutes,0), workoutEnergy=()=>state.workouts.reduce((a,b)=>a+b.calories,0);
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const img=(src,alt,cls='',eager=false)=>`<img src="${src}" alt="${esc(t(alt))}" class="${cls}" loading="${eager?'eager':'lazy'}" decoding="async" onload="this.classList.add('loaded')">`;
const aiOrb=(cls='')=>img(orb,'PulseFit AI glass orb',`ai-orb ${cls}`,true);
const person=(name=state.name,cls='')=>`<span class="avatar ${cls}" data-user-content>${esc(name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span>`;
const badge=(label,ico='')=>`<span class="status-badge">${ico?icon(ico):''}${t(label)}</span>`;
function topHeader(title,subtitle='',actions=''){return `<header class="dashboard-header"><div>${subtitle?`<p class="eyebrow">${t(subtitle)}</p>`:''}<h1>${t(title)}</h1></div><div class="row">${actions}</div></header>`}
function wellnessRing(size=''){return `<div class="wellness-ring ${size}" style="view-transition-name:wellness-ring"><svg viewBox="0 0 180 180" aria-label="${esc(t('Wellness breakdown'))}" role="img">${['blue','health','orange','purple'].map((c,i)=>`<circle cx="90" cy="90" r="73" transform="rotate(${i*90-84} 90 90)" pathLength="100" stroke="var(--color-${c})" stroke-dasharray="21.5 78.5"/>`).join('')}</svg><div class="wellness-ring-value"><strong data-count="${score()}" style="view-transition-name:wellness-score">${nf(score())}<small>%</small></strong><span>${t('In balance')}</span></div></div>`}
function wellnessHero(detail=false){return `<section class="global-wellness ${detail?'expanded':''}" style="view-transition-name:wellness-card"><div class="row between"><div><p class="eyebrow">${t('YOUR HEALTH, CONNECTED')}</p><h2 style="view-transition-name:wellness-title">${t('Global Wellness')}</h2></div>${ib(detail?'share':'arrow',detail?"share('Daily wellness')":"go('wellness')",detail?'Share':'Wellness details')}</div><div class="wellness-stage"><button class="wellness-score-button" onclick="${detail?"go('scoreInfo')":"go('wellness')"}" aria-label="${esc(t('View wellness details'))}">${wellnessRing()}</button><div class="wellness-ai">${aiOrb()}<div class="glass ai-status">${icon('activity')}<span>${t('General well-being')}<strong>+8 ${t('pts')}</strong></span></div></div></div><div class="wellness-legend">${[['Physical Activity',80,'blue','activity'],['Recovery',85,'health','report'],['Nutrition',75,'orange','article'],['Mental Health',90,'purple','article']].map(([label,n,c,p],i)=>`<button onclick="go('${p}','${i===2?'1':i===3?'4':''}')"><i style="background:var(--color-${c})"></i><span>${t(label)}</span><strong>${nf(n)}%</strong></button>`).join('')}</div><button class="ai-link" onclick="go('aiCoach')">${icon('activity')}<span>${t('AI recommendations')}</span>${icon('arrow')}</button></section>`}
function analytics(){return `<section class="analytics-card"><div class="row between"><h3>${t('Today Analytics')}</h3>${badge('On track')}</div><div class="analytics-bars">${[['Strength',45,'accent'],['Activity',25,'health'],['Nutrition',20,'orange'],['Hydration',10,'blue']].map(([l,n,c])=>`<button onclick="go('${l==='Strength'?'plan':l==='Activity'?'activity':l==='Hydration'?'task':'article'}','${l==='Hydration'?'Hydration check-in':l==='Nutrition'?'1':''}')" aria-label="${esc(t(l))}"><span class="thin-progress" style="--data-color:var(--color-${c})"><i style="width:${n*1.4+30}%"></i></span><span>${t(l)}<b>${nf(n)}%</b></span></button>`).join('')}</div></section>`}
function miniChart(type,color){let vals=[13,20,16,29,24,34,29,42,37,45,33,52];return `<svg class="metric-chart" viewBox="0 0 130 42" aria-hidden="true">${type==='wave'?`<path d="M0 22h21l5-5 4 5h10l5-13 6 29 6-34 6 25 5-7h17l5-6 5 6h13l5-10 5 17 5-7h7" stroke="var(--color-${color})" stroke-width="1.8" fill="none"/>`:type==='bars'?vals.map((n,i)=>`<rect x="${i*11}" y="${42-n*.7}" width="5" height="${n*.7}" rx="2" fill="var(--color-${color})" opacity="${.35+i*.05}"/>`).join(''):type==='area'?`<defs><linearGradient id="stepfill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="var(--color-${color})" stop-opacity=".65"/><stop offset="1" stop-color="var(--color-${color})" stop-opacity=".02"/></linearGradient></defs><path d="M0 36Q14 37 23 21T47 20T72 23T97 14T130 9V42H0Z" fill="url(#stepfill)"/><path d="M0 36Q14 37 23 21T47 20T72 23T97 14T130 9" fill="none" stroke="var(--color-${color})" stroke-width="2"/>`:`<path d="M1 6 13 8 25 5 36 17 49 14 61 22 74 18 87 29 101 25 114 33 129 31" fill="none" stroke="var(--color-${color})" stroke-width="2" stroke-linejoin="round"/>`}</svg>`}
function metricCard(label,value,unit,color,type,action,change,status){return `<button class="metric-card tone-${color}" onclick="${esc(action)}"><span class="metric-label"><i class="metric-icon ${color}">${icon(label==='Heart rate'?'heart':label==='Weight'?'weight':label==='Calories'?'flame':'activity')}</i>${t(label)}</span><div class="metric-number">${value}<small>${unit}</small></div>${miniChart(type,color)}<div class="metric-bottom"><span>${change}</span><small>${t(status)}</small></div></button>`}
function imageWorkout(label='Full body flow',action="go('workout','Full body flow')",cls=''){return `<button class="image-workout ${cls}" onclick="${esc(action)}"><div class="image-workout-photo" style="view-transition-name:workout-photo">${img(photo,'Woman stretching in sunlight','',true)}</div><span class="image-kicker">${icon('dumbbell')} ${t('YOUR DAILY RESET')}</span><div class="workout-glass glass"><div><h3 style="view-transition-name:workout-title">${t(label)}</h3><p>${nf(state.duration)} ${t('min')} · ${t(state.experience)}</p></div><span class="round-start">${icon('play')}</span></div></button>`}
function progressCards(){return `<div class="progress-grid">${[['Total workout',nf(state.workouts.length),'dumbbell','trainingHistory'],['Training time',nf(workoutMinutes())+' '+t('min'),'clock','trainingHistory'],['Calories',nf(energy(workoutEnergy()))+' '+energyUnit(),'flame','activity'],['Streak',nf(7)+' '+t('days'),'trophy','streak']].map(([l,v,i,p])=>`<button class="progress-tile" onclick="go('${p}')">${icon(i)}<span>${t(l)}</span><strong>${v}</strong></button>`).join('')}</div>`}
function recommendations(){return `<div class="recommendation-track">${[['Training','A little stronger','Make 20 minutes your own.',photo,"go('workout','Full body flow')"],['Nutrition','Colour your plate','Find a little balance.',foodPhoto,"go('article','1')"],['Recovery','Room to recover','Let your body reset.',yogaPhoto,"go('article','0')"],['Mental wellness','A moment for you','Pause. Breathe. Begin again.',orb,"go('article','4')"]].map(([category,title,body,src,action])=>`<button class="recommendation" onclick="${esc(action)}">${img(src,title)}<div><span class="eyebrow">${t(category)}</span><h3>${t(title)}</h3><p>${t(body)}</p>${icon('arrow')}</div></button>`).join('')}</div>`}
screens.home=()=>`<header class="dashboard-header home-header"><button class="identity-button" onclick="nav('profile')">${img('assets/avatar.webp',state.name,'avatar home-portrait',true)}<span class="greeting">${t('Good morning,')}</span></button><div class="row">${ib('search',"go('search')",'Search')}${ib('bell',"go('messages')",'Notifications')}</div></header><div class="daily-heading"><div><span class="date-line">${df(undefined,{weekday:'short',day:'numeric',month:'short'})}</span><h1>${t('Feel good. Live better.')}</h1></div><button class="streak-chip" onclick="go('streak')">${icon('flame')}<b>${nf(7)}</b></button></div>${wellnessHero()}${analytics()}${section('Your daily signals','See all',"go('data')")}<div class="metric-grid">${metricCard('Heart rate',nf(state.hearts[0]?.value||68),'bpm','coral','wave',"go('heart')",'−2 bpm','Resting')}${metricCard('Steps',nf(6248),t('steps'),'orange','area',"go('activity','Steps')",'+12%','vs yesterday')}${metricCard('Calories',nf(energy(284+workoutEnergy())),energyUnit(),'health','bars',"go('activity','Calories')",'+8%','vs yesterday')}${metricCard('Weight',weight(state.weight),state.unit==='metric'?'kg':'lb','accent','line',"go('body')",'−'+nf(state.unit==='metric'?.6:1.3)+' '+(state.unit==='metric'?'kg':'lb'),'this week')}</div>${section('Today’s Plan','View plan',"nav('plan')")}${imageWorkout()}${section('Your Progress','Weekly progress',"go('review')")}${progressCards()}${section('AI Recommendations','See all',"go('aiCoach')")}${recommendations()}<button class="weekly-report-row" onclick="go('report')"><span class="list-icon">${icon('plan')}</span><span><b>${t('Weekly Health Report')}</b><small>${t('Small steps. Real progress.')}</small></span>${icon('arrow')}</button>${healthNote()}`;
screens.wellness=()=>header('Global Wellness',ib('plan',"go('calendar')",'Daily records'))+wellnessHero(true)+tabs(['Day','Week','Month'],period,'setPeriod')+`<div class="wellness-activity"><span class="eyebrow">${t('Physical Activity')}</span><div class="row between"><h2>${t('A stronger daily rhythm')}</h2><strong>${nf(80)}%</strong></div><div class="mini-stats"><div><strong>${nf(6248)}</strong><small>${t('Steps')}</small></div><div><strong>${nf(energy(284+workoutEnergy()))}</strong><small>${energyUnit()}</small></div><div><strong>${nf(32+workoutMinutes())}</strong><small>${t('Active minutes')}</small></div></div>${chart(period==='Day'?[21,34,43,35,62,75,82]:period==='Month'?[42,54,61,70,68,79,82]:[54,68,62,75,70,80,82],true)}</div><div class="card mt">${row('How your score works','Movement, recovery and consistency','leaf',"go('scoreInfo')")}${row('Edit daily goals','','settings',"go('goals')")}${row('Heart rate history','','heart',"go('history')")}${row('Daily records','','plan',"go('calendar')")}</div>${healthNote()}`;
screens.aiCoach=()=>header('AI Recommendations')+`<div class="ai-coach-hero glass">${aiOrb()}<span class="eyebrow">PULSEFIT AI</span><h2>${t('A little insight.<br>A healthier rhythm.')}</h2><p>${t('Suggestions shaped around your daily balance.')}</p>${badge('Personalised for you','leaf')}</div>${recommendations()}<div class="card mt">${row('Review your weekly rhythm','See your progress and next steps','activity',"go('report')")}${row('Make your plan fit you','Adjust days, duration and intensity','settings',"go('adjust')")}</div>${healthNote()}`;
function renderDesktop(){document.querySelector('.studio').innerHTML=`<a class="wordmark" href="#home" onclick="event.preventDefault();nav('home')"><span class="brand-icon">${icon('activity')}</span>PulseFit<span class="tiny">®</span></a><div class="studio-bottom">${themeControl('desktop')}<span class="eyebrow">${t('A LITTLE EVERY DAY.')}</span><h1>${t('Find your<br>healthy rhythm.')}</h1><p>${t('A little movement.<br>A little more you.')}</p><div class="studio-line"></div><span class="tiny">${t('INTERACTIVE APP CONCEPT')} &nbsp; / &nbsp; 2026</span></div>`;document.querySelector('.notes').innerHTML=`<div class="desktop-orb">${aiOrb()}</div><span class="eyebrow">${t('WELLBEING, REIMAGINED')}</span>${[['01','Move with purpose.','Build your rhythm.'],['02','Know your body.','Find your balance.'],['03','Grow together.','Feel the difference.']].map(([n,a,b])=>`<div class="note"><span>${n}</span><p>${t(a)}<br><strong>${t(b)}</strong></p></div>`).join('')}<p class="demo-note">${t('Interactive prototype · Simulated data')}<br>${t('No real payments or health readings')}</p>${btn('Explore onboarding',"go('welcome')",'text-button')}`}
render=function(){clearInterval(timer);timer=null;const d=document.querySelector('.device'),app=document.getElementById('app'),navEl=document.getElementById('nav');d.classList.toggle('dark',state.theme==='dark');document.documentElement.lang=PF_I18N.locale(state.lang);const primary=['home','plan','community','profile'].includes(page);d.dataset.page=page;app.classList.toggle('has-nav',primary);navEl.style.display=primary?'grid':'none';if(!navEl.querySelector('.nav-indicator'))navEl.innerHTML=`<div class="nav-indicator"></div>${['home','plan','community','profile'].map(x=>`<button data-tab="${x}" onclick="nav('${x}')"><span class="nav-icon">${icon(x)}</span><span class="nav-label"></span></button>`).join('')}`;['home','plan','community','profile'].forEach((x,i)=>{let b=navEl.querySelector(`[data-tab="${x}"]`);b.classList.toggle('active',x===page);b.setAttribute('aria-label',t(x[0].toUpperCase()+x.slice(1)));b.setAttribute('aria-current',x===page?'page':'false');b.querySelector('.nav-label').textContent=t(x[0].toUpperCase()+x.slice(1));if(x===page)navEl.style.setProperty('--active-index',i)});app.innerHTML=`<div class="page">${(screens[page]||screens.home)()}</div>`;renderDesktop();PF_I18N.localize(app,state.lang);afterRender();};
// More redesigned routes and motion are appended below.
const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
function calendarStrip(){return `<div class="calendar-strip" style="--selected-day:${selectedDay}"><span class="calendar-indicator"></span>${weekdays.map((d,i)=>`<button class="${i===selectedDay?'active':''}" onclick="selectPlanDay(${i})" aria-label="${esc(t(d))}" aria-pressed="${i===selectedDay}"><span>${df(new Date(2026,8,14+i),{weekday:'short'})}</span><strong>${nf(14+i)}</strong><i class="${i<3?'complete':''}">${i<3?'✓':'·'}</i></button>`).join('')}</div>`}
const planTasks=[{name:'Full body flow',time:'08:00',duration:20,icon:'dumbbell',route:'workout'},{name:'Hydration check-in',time:'12:30',duration:2,icon:'activity',route:'task'},{name:'Evening wind-down',time:'18:00',duration:10,icon:'leaf',route:'workout'}];
function taskTimeline(){return `<div class="task-timeline">${planTasks.map((task,i)=>{const status=state.tasks?.[`${selectedDay}:${task.name}`]||state.tasks?.[task.name];return `<article class="timeline-item ${status===true?'task-done':status==='skipped'?'task-skipped':''}" data-task="${i}"><span class="task-time">${task.time}</span><span class="timeline-dot"></span><div class="timeline-card"><div class="row between"><span class="task-icon">${icon(status===true?'check':task.icon)}</span>${ib('more',`taskMore(${i})`,'More')}</div><h3>${t(task.name)}</h3><div class="row between"><span class="task-duration">${nf(task.duration)} ${t('min')}</span><button class="task-start ${status===true?'finished':''}" onclick="${status===true?`setTaskStatus(${i},false)`:`go('${task.route}','${task.name}')`}">${status===true?icon('check')+' '+t('Finished'):status==='skipped'?t('Restart'):t('Start')+icon('play')}</button></div></div></article>`}).join('')}</div>`}
function planWeekly(){const count=Math.min(state.workouts.length+Object.values(state.tasks||{}).filter(x=>x===true).length,state.frequency);return `<div class="plan-weekly card"><div class="row between"><h3>${t('Weekly progress')}</h3><span>${nf(Math.round(count/state.frequency*100))}%</span></div><div class="bar"><span style="width:${count/state.frequency*100}%"></span></div><div class="mini-stats"><div><strong>${nf(workoutMinutes())}</strong><small>${t('Training time')}</small></div><div><strong>${nf(state.workouts.length*5)}</strong><small>${t('Total volume')}</small></div><div><strong>${nf(85)}%</strong><small>${t('Recovery')}</small></div></div></div>`}
screens.plan=()=>state.planStatus==='deleted'?legacyScreens.plan():`${topHeader('Your plan','MOVE WITH INTENTION',ib('settings',"go('planSettings')",'Plan settings'))}<div class="plan-month row between"><span>${df(undefined,{month:'long',year:'numeric'})}</span>${btn('Full plan',"go('fullPlan')",'text-button')}</div>${calendarStrip()}<button class="plan-banner" onclick="go('fullPlan')">${img('assets/workout.webp','Your balanced training programme','',true)}<div class="plan-banner-shade"></div><div class="plan-banner-copy"><span class="image-kicker">${t('WEEK 2 OF 4')}</span><h2>${t('Build your<br>balance.')}</h2><p>${t(state.goal)} · ${nf(state.frequency)} ${t('days per week')}</p><span class="plan-banner-link">${t('Explore your plan')} ${icon('arrow')}</span></div></button>${state.workoutDraft?`<div class="resume-card glass"><h3>${t('Pick up where you left off')}</h3>${btn('Resume workout',"workIndex=state.workoutDraft.index;seconds=state.workoutDraft.seconds;rest=state.workoutDraft.rest;paused=false;go('player')",'primary mt')}</div>`:''}<div class="section-head"><h3 id="today-tasks-title">${t('Today’s rhythm')}</h3>${btn('View daily routine',"go('dayPlan',String(selectedDay))",'text-button')}</div><div id="timeline-holder">${taskTimeline()}</div><div id="weekly-holder">${planWeekly()}</div><div class="row mt">${btn('Adjust plan',"go('adjust')",'secondary')}${btn('Weekly review',"go('review')",'secondary')}</div>${section('Find your next favourite')}<div class="library-track"><button class="library-image-card" onclick="filter='All';go('library')">${img('assets/core-training.webp','Workout library')}<div><span>${t('Workout library')}</span>${icon('arrow')}</div></button><button class="library-image-card" onclick="go('movements')">${img(yogaPhoto,'Movement library')}<div><span>${t('Movement library')}</span>${icon('arrow')}</div></button></div>`;
function selectPlanDay(i){selectedDay=i;const strip=document.querySelector('.calendar-strip');if(!strip){render();return}strip.style.setProperty('--selected-day',i);strip.querySelectorAll('button').forEach((el,j)=>{el.classList.toggle('active',i===j);el.setAttribute('aria-pressed',String(i===j))});document.getElementById('today-tasks-title').textContent=t(weekdays[i]);const holder=document.getElementById('timeline-holder');holder.animate([{opacity:0,transform:'translateX(10px)'},{opacity:1,transform:'translateX(0)'}],{duration:reduced()?0:220,easing:'ease-out'});holder.innerHTML=taskTimeline();PF_I18N.localize(holder,state.lang)}
function taskMore(i){const task=planTasks[i];sheet(task.name,'Make this task work for your day.',btn('Mark complete',`closeSheet();setTaskStatus(${i},true)`)+btn('Skip today',`closeSheet();setTaskStatus(${i},'skipped')`,'secondary')+btn('Change time',`closeSheet();go('task','${task.name}')`,'secondary')+btn('Replace task',"closeSheet();go('library')",'secondary'))}
function setTaskStatus(i,status){state.tasks={...state.tasks,[`${selectedDay}:${planTasks[i].name}`]:status};save();const old=document.querySelector(`[data-task="${i}"]`);if(old&&!reduced())old.animate([{transform:'scale(1)'},{transform:'scale(.98)'},{transform:'scale(1)'}],{duration:250});document.getElementById('timeline-holder').innerHTML=taskTimeline();document.getElementById('weekly-holder').innerHTML=planWeekly();toast(status===true?'Task completed':status==='skipped'?'Task skipped for today':'Task updated');animateData()}
// Image-led community, preserving the existing posts, reactions, privacy and publish flow.
seededPosts[0].gallery=[runPhoto,yogaPhoto];seededPosts[1].gallery=['assets/workout.webp'];
const feedPhoto=p=>p.id==='s1'?runPhoto:p.id==='s2'?photo:p.image&&p.image!==true?p.image:foodPhoto;
function stories(){return `<div class="stories"><button class="story" onclick="openComposer()"><span class="story-ring own">${person()}<i>${icon('plus')}</i></span><span>${t('Your moment')}</span></button>${seededPosts.map((p,i)=>`<button class="story" onclick="go('user','${p.id}')"><span class="story-ring">${img(i?photo:yogaPhoto,p.name,'story-face')}<i>${icon('check')}</i></span><span data-user-content>${p.name.split(' ')[0]}</span></button>`).join('')}<button class="story" onclick="go('topics')"><span class="story-ring topic-story">${icon('leaf')}</span><span>${t('Small steps')}</span></button><button class="story" onclick="go('challengeProgress')"><span class="story-ring challenge-story">${icon('trophy')}</span><span>${t('Your wins')}</span></button></div>`}
function challengeBanner(){return `<section class="challenge-banner"><div><span class="eyebrow">${t('BETTER, TOGETHER')}</span><h2>${t('7 days.<br>A stronger you.')}</h2><p>${nf(1248)} ${t('participants')} · ${nf(state.checkins)} / 7</p><button class="challenge-join" onclick="go('challenge')">${t(state.joined?'Check your progress':'Join challenge')} ${icon('arrow')}</button></div><div class="challenge-photo">${img(yogaPhoto,'Move together outdoors')}<span>${icon('trophy')}</span></div></section>`}
function v2Post(p,detail=false){const gallery=p.gallery||(p.image?[p.image===true?runPhoto:p.image]:p.id==='s2'?[photo]:[]);const own=state.posts.some(x=>x.id===p.id);return `<article class="social-post" data-post-id="${p.id}"><header class="post-head"><button class="post-person" onclick="go('user','${p.id}')">${p.id.startsWith('s')?`<span class="avatar photo-avatar">${img(p.id==='s1'?yogaPhoto:photo,p.name)}</span>`:person(p.name)}<span><strong data-user-content>${esc(p.name)}</strong><small><span data-user-content>${esc(p.location||t('Your community'))}</span> · ${t(p.time||'Just now')}</small></span></button>${ib('more',`postMenu('${p.id}')`,'More')}</header>${gallery.length?`<div class="post-gallery ${gallery.length>1?'collage':''}">${gallery.map((src,i)=>`<button onclick="openPhoto('${p.id}',${i})" aria-label="${esc(t('Expand photo'))}">${img(src,'Community movement photo')}${i===1?`<span class="photo-overlay">${icon('plus')} ${t('Good company')}</span>`:''}</button>`).join('')}</div>`:''}${p.workout?`<button class="shared-workout-card" onclick="go('trainingHistory')">${icon('check')}<span>${t('WORKOUT COMPLETE')}<strong>${t('Full body flow')}</strong></span><b>${nf(state.duration)} ${t('min')}</b></button>`:''}<p class="post-text" ${own?'data-user-content':''}>${own?esc(p.text):t(p.text)}</p><button class="text-button tag" onclick="go('topic','${esc(p.topic||'SmallSteps')}')">#${esc(p.topic||'SmallSteps')}</button><div class="post-actions"><button class="reaction ${state.likes[p.id]?'active':''}" onclick="like('${p.id}')" aria-label="${esc(t('Like post'))}" aria-pressed="${!!state.likes[p.id]}">${icon('heart')}<span>${nf((p.likes||0)+(state.likes[p.id]?1:0))}</span></button><button onclick="openComments('${p.id}')" aria-label="${esc(t('Comments'))}">${icon('message')}<span>${nf((state.comments[p.id]||[]).length)}</span></button><button onclick="share('Community post')" aria-label="${esc(t('Share'))}">${icon('share')}</button><button class="save-post ${state.favorites.includes('post:'+p.id)?'is-saved':''}" onclick="favorite('post:${p.id}')" aria-label="${esc(t('Save post'))}" aria-pressed="${state.favorites.includes('post:'+p.id)}">${icon('bookmark')}</button></div>${!detail?btn('View conversation',`go('post','${p.id}')`,'post-detail-link'):''}</article>`}
postCard=v2Post;
screens.community=()=>`${topHeader('Community','',ib('search',"go('search')",'Search')+ib('message',"go('messages')",'Messages'))}<div class="community-tabs" style="--tab-index:${['For You','Following','Challenges'].indexOf(communityTab)}"><span></span>${['For You','Following','Challenges'].map(x=>`<button class="${x===communityTab?'active':''}" onclick="changeCommunity('${x}')">${t(x)}</button>`).join('')}</div><div id="community-content">${communityBody()}</div><button class="community-fab" onclick="openComposer()" aria-label="${esc(t('New post'))}">${icon('plus')}</button>`;
function communityBody(){return communityTab==='Challenges'?challengeList():`${stories()}${communityTab==='For You'?challengeBanner():''}<div class="section-head"><h3>${t(communityTab==='Following'?'From your people':'Good energy, shared')}</h3>${ib('activity','refreshFeed()','Refresh feed')}</div>${allPosts().filter(p=>communityTab!=='Following'||state.following.includes(p.name)||p.name===state.name).map(p=>v2Post(p)).join('')||`<div class="empty">${icon('community')}<h3>${t('Find your people')}</h3><p>${t('Follow someone from For You to see their updates here.')}</p>${btn('Explore the community',"changeCommunity('For You')",'primary mt')}</div>`}${btn('Explore topics',"go('topics')",'secondary mt')}`}
changeCommunity=function(tab){communityTab=tab;const holder=document.getElementById('community-content');if(!holder){render();return}document.querySelector('.community-tabs').style.setProperty('--tab-index',['For You','Following','Challenges'].indexOf(tab));document.querySelectorAll('.community-tabs button').forEach((b,i)=>b.classList.toggle('active',i===['For You','Following','Challenges'].indexOf(tab)));holder.innerHTML=communityBody();PF_I18N.localize(holder,state.lang);holder.animate([{opacity:.6,transform:'translateX(12px)'},{opacity:1,transform:'translateX(0)'}],{duration:reduced()?0:220,easing:'ease-out'})};
like=function(id){state.likes[id]=!state.likes[id];save();const p=allPosts().find(p=>p.id===id),el=document.querySelector(`[data-post-id="${id}"] .reaction`);if(el){el.classList.toggle('active',!!state.likes[id]);el.setAttribute('aria-pressed',String(!!state.likes[id]));el.querySelector('span').textContent=nf((p?.likes||0)+(state.likes[id]?1:0));if(!reduced())el.querySelector('svg').animate([{transform:'scale(1)'},{transform:'scale(1.28)'},{transform:'scale(1)'}],{duration:280,easing:'cubic-bezier(.34,1.38,.64,1)'})}else render()};
const oldFavorite=favorite;
favorite=function(id){const enabled=!state.favorites.includes(id);state.favorites=enabled?[...state.favorites,id]:state.favorites.filter(x=>x!==id);save();toast(enabled?'Saved to your favourites':'Removed from saved');if(id.startsWith('post:')){document.querySelectorAll(`[data-post-id="${id.slice(5)}"] .save-post`).forEach(el=>{el.classList.toggle('is-saved',enabled);el.setAttribute('aria-pressed',String(enabled))})}else{const btn=document.querySelector('.page-header button[aria-label="'+t('Save workout')+'"],.page-header button[aria-label="'+t('Save article')+'"],.page-header button[aria-label="'+t('Save movement')+'"]');btn?.classList.toggle('is-saved',enabled)}if(page==='favorites')render()};
function openComments(id){window.commentPostId=id;sheet('Conversation','A little encouragement goes a long way.',`<div class="sheet-comments" id="sheet-comments">${commentsHtml(id)}</div><label class="form-field"><span>${t('Your comment')}</span><input id="sheet-comment" placeholder="${esc(t('Leave a little encouragement…'))}" onkeydown="if(event.key==='Enter')submitSheetComment()"></label>${btn('Post comment','submitSheetComment()')}`)}
function commentsHtml(id){return (state.comments[id]||[]).map(c=>`<div class="comment-row">${person()}<div><b data-user-content>${esc(state.name)}</b><p data-user-content>${esc(c)}</p></div></div>`).join('')||`<div class="empty"><p>${t('Start a kind conversation.')}</p></div>`}
function submitSheetComment(){const value=val('sheet-comment').trim();if(!value){toast('Write something before posting');return}state.comments[window.commentPostId]=[...(state.comments[window.commentPostId]||[]),value];save();document.getElementById('sheet-comments').innerHTML=commentsHtml(window.commentPostId);document.getElementById('sheet-comment').value='';document.querySelectorAll(`[data-post-id="${window.commentPostId}"] .post-actions button:nth-child(2) span`).forEach(el=>el.textContent=nf(state.comments[window.commentPostId].length));toast('Comment added')}
screens.post=()=>{const p=allPosts().find(p=>p.id===param);return header('A shared moment')+(p?v2Post(p,true)+section('Conversation')+`<div class="card">${commentsHtml(p.id)}</div>`+field('Your comment','comment','')+btn('Post comment','comment()'):`<div class="empty">${t('This content is no longer available.')}</div>`)};
function openPhoto(id,index){const p=allPosts().find(p=>p.id===id),sources=p?.gallery||(p?.image?[p.image===true?runPhoto:p.image]:[photo]);const src=sources[index]||sources[0];window.currentPhoto={id,index};previousFocus=document.activeElement;document.getElementById('app').inert=true;document.getElementById('nav').inert=true;document.getElementById('overlay').innerHTML=`<div class="photo-viewer" role="dialog" aria-modal="true" aria-label="${esc(t('Photo preview'))}"><header>${ib('close','closeSheet()','Close')}<span>${nf(index+1)} / ${nf(sources.length)}</span>${ib('share',"share('Community post')",'Share')}</header>${img(src,'Community movement photo','full-photo',true)}<p data-user-content>${esc(p?.name||'PulseFit')}</p>${sources.length>1?`<div class="photo-pager">${sources.map((x,i)=>btn(String(i+1),`openPhoto('${id}',${i})`,i===index?'primary':'secondary')).join('')}</div>`:''}</div>`;document.querySelector('.photo-viewer button').focus()}
function openComposer(){sheet('Share your little win','Choose the kind of moment you want to share.',`<div class="compose-types">${[['Workout check-in','dumbbell'],['Challenge progress','trophy'],['Achievement','leaf'],['Photo & text','camera']].map(([label,i])=>`<button onclick="choosePostType('${label}')">${icon(i)}<span>${t(label)}</span></button>`).join('')}</div>${state.draft?btn('Continue your draft',"closeSheet();go('compose')",'secondary mt'):''}`)}
function choosePostType(type){state.selectedPostType=type;state.attachWorkout=type==='Workout check-in';save();closeSheet();go('compose')}
function refreshFeed(){const holder=document.getElementById('community-content');holder.classList.add('refreshing');toast('Refreshing your community…');setTimeout(()=>{holder.innerHTML=communityBody();holder.classList.remove('refreshing');toast('You’re all caught up.')},600)}
// A more compact personal space, all original destinations retained.
screens.profile=()=>`${topHeader('My space','',ib('settings',"go('settings')",'Settings'))}<section class="profile-v5"><div class="profile-v5-identity"><div class="portrait-ring">${img('assets/avatar.webp',state.name,'profile-monogram portrait-photo',true)}</div><div class="profile-v5-name"><h2 data-user-content>${esc(state.name)}</h2><p>${t(state.goal)}</p>${badge(state.member?'PulseFit Plus':'Free member')}</div>${ib('edit',"go('editProfile')",'Edit profile')}</div><div class="profile-v5-stats">${[['Workouts',state.workouts.length,'trainingHistory'],['Total minutes',workoutMinutes(),'trainingHistory'],['Streak',7,'streak']].map(([label,value,route])=>`<button onclick="go('${route}')"><strong>${nf(value)}</strong><span>${t(label)}</span></button>`).join('')}</div><button class="profile-v5-membership" onclick="go('membership')">${img(photo,'Movement in bright natural light','membership-photo',true)}<span class="membership-v8-copy"><b>PulseFit Plus</b><small>${t(state.member?'Manage membership':'More support, every day.')}</small><span class="membership-v8-cta">${t(state.member?'Membership':'Upgrade')} ${icon('arrow')}</span></span></button><div class="profile-v5-shortcuts">${[['Health profile','heart','healthProfile',nf(score()),'%'],['My data','activity','data',weight(state.weight),state.unit==='metric'?'kg':'lb'],['Training history','clock','trainingHistory',nf(workoutMinutes()),t('min')],['Achievements','trophy','achievements',nf(state.checkins>=7?3:2),'']].map(([label,i,route,value,unit])=>`<button onclick="go('${route}')"><span class="shortcut-symbol">${icon(i)}</span><strong>${t(label)}</strong><span class="shortcut-value">${value}<small>${unit}</small></span><span class="shortcut-arrow" aria-hidden="true">${icon('arrow')}</span></button>`).join('')}</div><div class="profile-v5-menu">${[['Favourites','bookmark','favorites'],['Connected devices','device','devices'],['Settings','settings','settings'],['Privacy & permissions','shield','permissions'],['Help & support','message','help']].map(([label,i,route])=>`<button onclick="go('${route}')">${icon(i)}<span>${t(label)}</span>${icon('chevron')}</button>`).join('')}</div></section>`;
screens.welcome=()=>`<section class="welcome-v2"><div class="welcome-top"><span class="welcome-brand">${icon('activity')} PulseFit</span>${btn('Explore demo',"nav('home')",'text-button')}</div><div class="welcome-photo">${img(photo,'Movement in bright natural light','',true)}<div class="welcome-photo-tint"></div><span class="welcome-photo-badge glass">${icon('activity')} ${t('MOVE. FEEL. THRIVE.')}</span></div><div class="welcome-panel"><div class="welcome-orb">${aiOrb()}</div><span class="eyebrow">${t('A LITTLE EVERY DAY.')}</span><h1>${t('Build a healthier<br>rhythm.')}</h1><p>${t('Movement, balance and a little more you.')}</p><div class="welcome-actions">${btn('Continue with Apple',"mockLogin('Apple')")}${btn('Continue with Google',"mockLogin('Google')",'secondary')}${btn('Continue with Email',"go('login')",'secondary')}${btn('Continue as Guest',"startOnboarding()",'text-button')}</div><p class="disclaimer">${t('By continuing, you agree to our')}<br>${btn('Terms',"go('legal','Terms of Service')",'text-button')} · ${btn('Privacy',"go('legal','Privacy Policy')",'text-button')}</p></div></section>`;
screens.splash=()=>`<div class="splash-v2">${aiOrb()}<h1>PulseFit</h1><p>${t('Finding your rhythm…')}</p><div class="skeleton-line"></div></div>`;
screens.generating=()=>header('Your personal plan')+`<div class="generation-v2">${aiOrb()}<h2>${t('Finding your rhythm…')}</h2><p class="subtitle">${t('Bringing your goals, preferences and weekly routine together.')}</p><div class="generation-skeleton"><div class="skeleton-line"></div><div class="skeleton-line"></div><div class="skeleton-line"></div></div><div class="bar"><span id="generatebar" style="width:12%"></span></div></div>`;
const oldWorkout=screens.workout;
screens.workout=()=>oldWorkout().replace('class="exercise-visual"','class="exercise-visual shared-workout-detail" style="view-transition-name:workout-photo"').replace('<h2 class="mt">','<h2 class="mt" style="view-transition-name:workout-title">');
const originalComplete=completeWorkout;
completeWorkout=function(community){state.tasks={...state.tasks,[`${selectedDay}:Full body flow`]:true};originalComplete(community)};
const originalCompose=screens.compose;
screens.compose=()=>originalCompose().replace('<option value="'+(state.selectedPostType||'Photo & text')+'"','<option selected value="'+(state.selectedPostType||'Photo & text')+'"');
// Unified navigation motion: real shared-element snapshots when supported.
let transitionBusy=false,routeDirection='forward',activeViewTransition=null,lastToastKey='',sheetDrag=null;
function transitionRoute(change,kind='forward'){
 activeViewTransition?.skipTransition();transitionBusy=false;
 document.querySelectorAll('#app .page').forEach(el=>el.getAnimations().forEach(animation=>animation.cancel()));
 change();
 const content=document.querySelector('#app .page');
 if(content&&!reduced())content.animate([{opacity:.65},{opacity:1}],{duration:160,easing:'ease-out'});
}

go=function(p,arg=''){if(p==='language'){openLanguageSheet();return}if(p==='units'){openUnitsSheet();return}transitionRoute(()=>legacyGo(p,arg),'forward')};
nav=function(p){const tabs=['home','plan','community','profile'];if(p===page){document.getElementById('app').scrollTo({top:0,behavior:reduced()?'instant':'smooth'});return}const dir=tabs.indexOf(p)<tabs.indexOf(page)?'tab-left':'tab-right';transitionRoute(()=>legacyNav(p),dir)};
backNow=function(){transitionRoute(()=>legacyBack(),'back')};
// Keep native browser back history aligned with the navigation stack.
window.onpopstate=e=>{if(document.getElementById('overlay').innerHTML){closeSheet();return}const target=e.state?.page||decodeURIComponent(location.hash.slice(1)).split('=')[0]||'home';transitionRoute(()=>{const matching=prev.findLastIndex(x=>x.page===target);let restore=matching>=0?prev[matching]:{page:target,param:e.state?.param||'',scroll:scrolls[target]||0};if(matching>=0)prev=prev.slice(0,matching);page=screens[target]?target:'home';param=restore.param||'';render();document.getElementById('app').scrollTop=restore.scroll||0},'back')};
// Modal/sheet lifecycle, keyboard focus and touch dismissal.
sheet=function(title,body,actions){previousFocus=document.activeElement;const overlay=document.getElementById('overlay');document.getElementById('app').inert=true;document.getElementById('nav').inert=true;overlay.innerHTML=`<div class="scrim" onclick="if(event.target===this)closeSheet()"><section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(t(title))}"><div class="sheet-handle" aria-label="${esc(t('Drag down to close'))}"></div><div class="row between"><h2>${t(title)}</h2>${ib('close','closeSheet()','Close')}</div>${body?`<p>${t(body)}</p>`:''}${actions}</section></div>`;PF_I18N.localize(overlay,state.lang);bindSheetDismiss();requestAnimationFrame(()=>overlay.querySelector('button')?.focus())};
closeSheet=function(){const overlay=document.getElementById('overlay'),scrim=overlay.querySelector('.scrim'),panel=overlay.querySelector('.sheet,.photo-viewer');document.getElementById('app').inert=false;document.getElementById('nav').inert=false;const closingNode=overlay.firstElementChild;if(!closingNode)return;if(reduced()){closingNode.remove();previousFocus?.focus?.();return}scrim?.classList.add('closing');panel?.classList.add('closing');if(panel?.classList.contains('photo-viewer'))panel.animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.96)'}],{duration:180,fill:'forwards'});closingNode.style.pointerEvents='none';setTimeout(()=>{if(closingNode.isConnected)closingNode.remove();previousFocus?.focus?.()},220)};
function bindSheetDismiss(){const panel=document.querySelector('.sheet'),handle=panel?.querySelector('.sheet-handle');if(!panel||!handle)return;handle.addEventListener('pointerdown',e=>{sheetDrag={y:e.clientY,pointer:e.pointerId};handle.setPointerCapture(e.pointerId)});handle.addEventListener('pointermove',e=>{if(!sheetDrag)return;const delta=Math.max(0,e.clientY-sheetDrag.y);panel.style.transform=`translateY(${delta}px)`});handle.addEventListener('pointerup',e=>{if(!sheetDrag)return;const delta=e.clientY-sheetDrag.y;sheetDrag=null;panel.style.transform='';if(delta>70)closeSheet()});}
document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const dialog=document.querySelector('#overlay [role=dialog]');if(!dialog)return;const focusables=[...dialog.querySelectorAll('button,input,select,textarea,a[href]')].filter(x=>!x.disabled);if(!focusables.length)return;if(e.shiftKey&&document.activeElement===focusables[0]){e.preventDefault();focusables.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===focusables.at(-1)){e.preventDefault();focusables[0].focus()}});
confirmAction=function(title,action){sheet(title,'This action changes your saved demo data.',btn('Confirm',`closeSheet();${action}`)+btn('Cancel','closeSheet()','secondary'));document.querySelector('.scrim').classList.add('modal-scrim');document.querySelector('.sheet').classList.add('center-modal')};
toast=function(msg){lastToastKey=msg;const el=document.getElementById('toast');el.textContent=t(msg);el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)};
function openLanguageSheet(){sheet('Language','Choose the language that feels like home.',`<div class="language-options">${Object.entries(PF_I18N.names).map(([code,label])=>`<button class="option ${state.lang===code?'selected':''}" onclick="setLanguage('${code}')" aria-pressed="${state.lang===code}"><span data-native-language>${label}</span><span class="check">${state.lang===code?'✓':''}</span></button>`).join('')}</div>${btn('Done','closeSheet()','primary mt')}`)}
function setLanguage(lang){if(!Object.hasOwn(PF_I18N.names,lang))return;const oldLang=state.lang;const values=[...document.querySelectorAll('#app input[id],#app textarea[id],#app select[id]')].map(el=>({id:el.id,value:el.value,checked:el.checked})),scroll=document.getElementById('app').scrollTop;state.lang=lang;save();render();values.forEach(v=>{const el=document.getElementById(v.id);if(el){el.value=v.value;if(el.type==='checkbox')el.checked=v.checked}});document.getElementById('app').scrollTop=scroll;const overlay=document.getElementById('overlay');if(overlay.querySelector('.language-options'))openLanguageSheet();else PF_I18N.localize(overlay,lang,oldLang);if(document.getElementById('toast').classList.contains('show'))document.getElementById('toast').textContent=t(lastToastKey);toast('Language updated')}
screens.language=()=>header('Language')+`<div class="language-options stack">${Object.entries(PF_I18N.names).map(([code,label])=>`<button class="option ${state.lang===code?'selected':''}" onclick="setLanguage('${code}')"><span data-native-language>${label}</span><span class="check">${state.lang===code?'✓':''}</span></button>`).join('')}</div>`;
function openUnitsSheet(){sheet('Your units','Your numbers, the way you know them.',`<div class="stack">${option('Metric',state.unit==='metric'?'Metric':'Imperial',"setUnit('metric')",'kg · cm · km · kcal')}${option('Imperial',state.unit==='imperial'?'Imperial':'Metric',"setUnit('imperial')",'lb · ft · mi · kJ')}</div>${select('Date format','dateformat',['DD/MM/YYYY','MM/DD/YYYY','YYYY-MM-DD'],state.dateformat||'DD/MM/YYYY')}${select('Time zone','timezone',['Europe/Amsterdam','Europe/Berlin','Europe/Paris','Europe/London','Asia/Shanghai','Asia/Tokyo'],state.timezone||'Europe/Amsterdam')}${btn('Save preferences',"state.dateformat=val('dateformat');state.timezone=val('timezone');save();closeSheet();render();toast('Preferences updated')",'primary mt')}`)}
function setUnit(unit){if(!['metric','imperial'].includes(unit))return;state.unit=unit;save();const pos=document.getElementById('app').scrollTop;render();document.getElementById('app').scrollTop=pos;openUnitsSheet()}
const animatedData=new Map();
function animateData(){const signature=page+':'+JSON.stringify([state.workouts.length,state.hearts.length,state.weight,state.tasks,state.lang]);if(animatedData.has(signature)||reduced())return;animatedData.set(signature,true);document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count,small=el.querySelector('small')?.outerHTML||'';let start=performance.now();const run=now=>{if(!el.isConnected)return;const p=Math.min(1,(now-start)/350),value=Math.round(target*(1-(1-p)**3));el.innerHTML=nf(value)+small;if(p<1)requestAnimationFrame(run)};requestAnimationFrame(run)});document.querySelectorAll('.wellness-ring circle').forEach(el=>el.animate([{strokeDashoffset:21.5,opacity:.3},{strokeDashoffset:0,opacity:1}],{duration:350,easing:'cubic-bezier(.22,1,.36,1)'}));document.querySelectorAll('.metric-chart path,.chart path[fill="none"]').forEach(el=>{if(!el.getTotalLength)return;const n=el.getTotalLength();el.animate([{strokeDasharray:n,strokeDashoffset:n},{strokeDasharray:n,strokeDashoffset:0}],{duration:340,easing:'ease-out'})});document.querySelectorAll('.metric-chart rect,.chart rect').forEach(el=>{el.style.transformOrigin='center bottom';el.style.transformBox='fill-box';el.animate([{transform:'scaleY(.05)'},{transform:'scaleY(1)'}],{duration:320,easing:'ease-out'})})}
function formatRecordDate(value,withTime=false){let d=new Date(value);if(Number.isNaN(+d)){const match=String(value).match(/(\d+) Sep(?:, (\d+):(\d+))?/);d=match?new Date(2026,8,+match[1],+(match[2]||12),+(match[3]||0)):new Date(2026,8,18)}return df(d,withTime?{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'short'})}
afterRender=function(){legacyAfter();document.documentElement.lang=PF_I18N.locale(state.lang);document.querySelectorAll('#app img').forEach(el=>{if(el.complete)el.classList.add('loaded')});const app=document.getElementById('app');app.onscroll=()=>app.querySelector('.dashboard-header')?.classList.toggle('scrolled',app.scrollTop>20);const scope=document.querySelector('#app .page');if(scope){scope.dataset.route=page;scope.classList.toggle('large-copy',state.textSize==='Large');if(page==='complete'||page==='paymentSuccess'||page==='published')scope.classList.add('success-page')}animateData();PF_I18N.localize(app,state.lang);if(page==='compose'&&state.selectedPostType)document.getElementById('posttype').value=state.selectedPostType;};
// Horizontal and downward touch gestures remain optional; buttons provide the same actions.
let touchOrigin=null;document.getElementById('app').addEventListener('touchstart',e=>{if(page==='community'&&document.getElementById('app').scrollTop<=1)touchOrigin=e.touches[0].clientY;},{passive:true});document.getElementById('app').addEventListener('touchend',e=>{if(touchOrigin!==null&&e.changedTouches[0].clientY-touchOrigin>85&&page==='community')refreshFeed();touchOrigin=null},{passive:true});
// Localised image export shares exactly the language visible in the interface.
downloadCard=function(title){const c=document.createElement('canvas');c.width=900;c.height=1100;const ctx=c.getContext('2d'),g=ctx.createLinearGradient(0,0,900,1100);g.addColorStop(0,'#5674FF');g.addColorStop(1,'#8B7CFF');ctx.fillStyle=g;ctx.fillRect(0,0,900,1100);ctx.fillStyle='#fff';ctx.font='600 31px Manrope, sans-serif';ctx.fillText('PULSEFIT',72,104);ctx.fillStyle='#ffffff26';ctx.beginPath();ctx.roundRect(48,175,804,830,44);ctx.fill();ctx.fillStyle='#fff';ctx.font='500 44px sans-serif';const wrap=(text,x,y,maxWidth,lineHeight)=>{let line='';for(const ch of [...text]){if(ctx.measureText(line+ch).width>maxWidth){ctx.fillText(line,x,y);line='';y+=lineHeight}line+=ch}ctx.fillText(line,x,y);return y};wrap(t(title),85,268,720,58);ctx.font='500 34px sans-serif';ctx.fillText(state.name,85,420);ctx.fillStyle='#D9FF63';ctx.font='500 112px Manrope, sans-serif';ctx.fillText(title.includes('certificate')?nf(7)+' / 7':title.includes('Heart')?nf(state.hearts[0]?.value||72):nf(score())+'%',85,635);ctx.fillStyle='#fff';ctx.font='30px sans-serif';wrap(t('Small steps. A lasting rhythm.'),85,786,720,44);ctx.font='23px sans-serif';ctx.fillText(t('Simulated demo data')+' · '+df(undefined,{month:'long',year:'numeric'}),85,952);const a=document.createElement('a');a.download='pulsefit-share.png';a.href=c.toDataURL('image/png');a.click();toast('Your image is ready')};
// Keep page chrome outside the scrolling content's visual rhythm.
const beforeChromeRender=afterRender;
afterRender=function(){
 chromeFooterObserver?.disconnect();
 document.getElementById('page-actions')?.remove();
 beforeChromeRender();
 const app=document.getElementById('app'),scope=app.querySelector('.page');
 document.querySelector('.device').classList.remove('chrome-scrolled');
 const heading=scope?.querySelector(':scope > .dashboard-header, :scope > .page-header');
 if(heading){
  heading.classList.add('scroll-header');
  const update=()=>{const compact=app.scrollTop>32;heading.classList.toggle('scrolled',compact);document.querySelector('.device').classList.toggle('chrome-scrolled',compact)};
  app.onscroll=update;update();requestAnimationFrame(update);
 }
 app.classList.remove('has-page-actions');app.style.removeProperty('--action-space');
 if(!app.classList.contains('has-nav')&&heading){
  const direct=[...scope.children],primary=direct.filter(el=>el.matches('button.primary'));
  let actions=[];
  if(page==='exercise')actions=direct.filter(el=>el.matches('button.secondary'));
  else if(primary.length){const main=primary.at(-1);actions=[main];let next=main.nextElementSibling;while(next?.matches('button.secondary,button.text-button')){actions.push(next);next=next.nextElementSibling}}
  if(actions.length){
   const footer=document.createElement('div');footer.id='page-actions';footer.className='page-actions';
   actions.forEach(el=>{el.classList.remove('mt');footer.append(el)});
   if(actions.length===2&&page==='exercise')footer.classList.add('paired-actions');
   document.querySelector('.device').append(footer);app.classList.add('has-page-actions');
   PF_I18N.localize(footer,state.lang);
   const size=()=>app.style.setProperty('--action-space',(footer.offsetHeight+24)+'px');size();
   chromeFooterObserver?.disconnect();chromeFooterObserver=new ResizeObserver(size);chromeFooterObserver.observe(footer);
  }
 }
};
let chromeFooterObserver=null;
new MutationObserver(()=>{const footer=document.getElementById('page-actions');if(footer)footer.inert=!!document.getElementById('overlay').children.length}).observe(document.getElementById('overlay'),{childList:true});
// Explicit demo session state. First-run setup is separate from plan editing.
paths.community='M4 3h13a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3H9l-5 4V6a3 3 0 0 1 3-3M8 7h8M8 11h5M14 19h4l3 2v-6';
let setupStage=0;
const setupOrder=[1,4,0,2,3],originalOnboarding=screens.onboarding,originalOnboardNext=onboardNext;
startOnboarding=function(){flowMode='setup';setupStage=0;draftAnswers={...state,permissions:{...state.permissions},goal:state.goal||'Stay active'};go('intro')};
screens.intro=()=>header('Your personal plan')+`<section class="intro-coach"><div class="intro-coach-photo">${img(photo,'Movement in bright natural light','',true)}<span class="intro-coach-badge glass">${icon('leaf')} ${t('Personalised for you')}</span></div><h2>${t('Build a healthier<br>rhythm.')}</h2><p>${t('Bringing your goals, preferences and weekly routine together.')}</p><div class="intro-pill-row">${['Health profile','Privacy & permissions','Preferred movement'].map(x=>`<span>${t(x)}</span>`).join('')}</div></section>`+btn('Continue',"setupStage=0;go('onboarding')",'primary mt');
screens.onboarding=function(){if(flowMode!=='setup')return originalOnboarding();onboardStep=setupOrder[setupStage];let html=originalOnboarding();html=html.replace(/<p class="step-label">.*?<\/p>/,`<p class="step-label">${t('STEP')} ${setupStage+1} / 5</p>`).replace(/style="width:\d+%"/,`style="width:${(setupStage+1)*20}%"`);const start=html.indexOf('<div class="onboarding-bottom">');return html.slice(0,start)+`<div class="onboarding-bottom">${btn(setupStage===4?'Start my journey':'Next','onboardNext()')}${setupStage?btn('Previous step','setupStage--;render()','text-button'):''}</div>`};
onboardNext=function(){if(flowMode!=='setup')return originalOnboardNext();if(setupStage===0){let a=+val('age'),h=+val('height'),w=+val('weight'),tg=+val('target');if(draftAnswers.unit==='imperial'){h*=30.48;w/=2.20462;tg/=2.20462}if(a<18||a>100||h<100||h>240||w<30||w>300||tg<30||tg>300){document.getElementById('formerror').textContent=t('Check your age (18–100), height and weight.');return}Object.assign(draftAnswers,{age:a,height:h,weight:w,target:tg,gender:val('gender')})}if(setupStage===3)Object.assign(draftAnswers,{experience:val('experience'),duration:+val('duration'),equipment:val('equipment'),movement:val('movement'),injury:val('injury')});if(setupStage<4){setupStage++;render();document.getElementById('app').scrollTop=0}else{Object.assign(state,draftAnswers,{onboarded:true});save();flowMode='onboard';prev=[];nav('home');toast('Your new plan is ready')}};
function completeDemoLogin(){state.loggedIn=true;save();closeSheet();state.onboarded?nav('home'):startOnboarding()}
mockLogin=function(provider){sheet('Demo sign-in',`${provider} sign-in is simulated. No external account is connected.`,btn('Continue','completeDemoLogin()'))};
const profileSignedIn=screens.profile;
screens.profile=()=>{if(state.loggedIn)return profileSignedIn();return topHeader('My space','',ib('settings',"go('settings')",'Settings'))+`<section class="guest-profile card"><span class="guest-avatar">${icon('profile')}</span><h2>${t('Welcome back')}</h2><p>${t('Your next small step starts here.')}</p>${btn('Log in',"go('welcome')")}${btn('Create account',"go('register')",'secondary mt')}</section>`+section('Your preferences')+`<div class="card">${row('Language',PF_I18N.names[state.lang],'globe',"go('language')")}${row('Privacy & permissions','Your data, your choice','shield',"go('permissions')")}${row('Help & support','','message',"go('help')")}</div>`};
const welcomeWithProviders=screens.welcome;
screens.welcome=()=>welcomeWithProviders().replace(btn('Explore demo',"nav('home')",'text-button'),'').replace('<div class="welcome-actions">','<div class="welcome-actions">'+btn('Log in',"go('login')"));

// Content-bound images stay consistent between a card and its detail route.
const courseCovers={'Full body flow':photo,'Morning mobility':'assets/workout.webp','Evening wind-down':yogaPhoto,'Energising core':'assets/core-training.webp','Fresh air intervals':runPhoto};
const courseCover=name=>courseCovers[name]||photo;
paths.bell='M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4';
// Symmetric sliders are easier to recognise at small sizes than the old gear.
paths.settings='M4 7h4M12 7h8M4 17h8M16 17h4M8 4v6h4V4H8ZM12 14v6h4v-6h-4Z';
function openPlanPicker(id){const selectEl=document.getElementById(id);if(!selectEl)return;const title=selectEl.closest('.form-field').querySelector('span').textContent;sheet(title,'',`<div class="plan-picker-options" role="radiogroup" aria-label="${esc(title)}">${[...selectEl.options].map(o=>`<button class="option ${o.selected?'selected':''}" role="radio" aria-checked="${o.selected}" onclick="choosePlanOption('${id}','${esc(o.value)}')"><span>${esc(o.text)}</span><span class="check">${o.selected?icon('check'):''}</span></button>`).join('')}</div>`)}
function choosePlanOption(id,value){const field=document.getElementById(id);field.value=value;const trigger=document.querySelector(`[data-select-id="${id}"]`);trigger.querySelector('.picker-value').textContent=field.selectedOptions[0].text;trigger.setAttribute('aria-expanded','false');closeSheet();trigger.focus()}
const beforePickerRender=afterRender;
afterRender=function(){beforePickerRender();if(page!=='adjust')return;document.querySelectorAll('#app select').forEach(el=>{const label=el.closest('.form-field').querySelector('span');el.hidden=true;el.tabIndex=-1;const trigger=document.createElement('button');trigger.type='button';trigger.className='plan-picker-trigger';trigger.dataset.selectId=el.id;trigger.setAttribute('aria-label',label.textContent);trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-expanded','false');trigger.innerHTML=`<span class="picker-value">${esc(el.selectedOptions[0].text)}</span>${icon('chevron')}`;trigger.onclick=()=>{trigger.setAttribute('aria-expanded','true');openPlanPicker(el.id)};el.after(trigger)})};
const pickerClose=closeSheet;closeSheet=function(){document.querySelectorAll('.plan-picker-trigger').forEach(el=>el.setAttribute('aria-expanded','false'));pickerClose()};
const pickerLanguage=setLanguage;setLanguage=function(lang){pickerLanguage(lang);document.querySelectorAll('.plan-picker-trigger').forEach(el=>{el.querySelector('.picker-value').textContent=document.getElementById(el.dataset.selectId).selectedOptions[0].text})};
const detailWithCover=screens.workout;screens.workout=()=>detailWithCover().replace(`src="${photo}"`,`src="${courseCover(param||'Full body flow')}"`);
const exerciseWithCover=screens.exercise;screens.exercise=()=>exerciseWithCover().replace(`src="${photo}"`,`src="${[courseCovers['Morning mobility'],courseCovers['Energising core'],photo,courseCovers['Energising core'],yogaPhoto][+param||0]}"`);
// A single persisted preference drives the presentation canvas and the app.
paths.moon='M20.9 13.1A9 9 0 0 1 10.9 3.1 9 9 0 1 0 20.9 13.1Z';
function themeControl(location){return `<div class="theme-switch" data-theme-control="${location}" role="group" aria-label="${esc(t('Appearance'))}">${['light','dark'].map(mode=>`<button type="button" data-theme="${mode}" onclick="setTheme('${mode}')" aria-label="${esc(t(mode==='light'?'Light':'Dark'))}" aria-pressed="${state.theme===mode}" title="${esc(t(mode==='light'?'Light':'Dark'))}">${icon(mode==='light'?'sun':'moon')}${location==='desktop'?'':`<span>${t(mode==='light'?'Light':'Dark')}</span>`}</button>`).join('')}</div>`}
function syncTheme(){const dark=state.theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';document.querySelector('.device').classList.toggle('dark',dark);document.querySelectorAll('[data-theme-control] button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===state.theme)));document.querySelector('meta[name="theme-color"]').content=dark?'#171b28':'#edf1fc'}
function setTheme(mode){if(!['light','dark'].includes(mode))return;state.theme=mode;save();syncTheme()}
const themeAfterRender=afterRender;afterRender=function(){themeAfterRender();syncTheme()};
const settingsBeforeTheme=screens.settings;screens.settings=()=>settingsBeforeTheme().replace(row('Appearance',state.theme==='dark'?'Dark':'Light','sun',"go('appearance')"),`<div class="settings-theme"><span>${t('Appearance')}</span>${themeControl('settings')}</div>`);
screens.appearance=()=>header('Appearance')+`<div class="card appearance-card">${themeControl('appearance')}</div>`+btn('Done','back()','primary mt');
const coverPreview=new URLSearchParams(location.search).get('cover')==='1';
page=coverPreview?'home':'login';param='';history.replaceState({page,param},'',coverPreview?'#home':'#login');render();
