const cases={parking:{n:'01',en:'ARRIVE WITH CONFIDENCE',title:'把停车的不确定，\n留在出发之前。',quote:'“现在过去还有车位吗？我今天停车免费吗？”',ux:'直接回答是否有余位，优先展示剩余量；总容量不再占据首要位置，降低阅读负担。',interaction:'余位卡片 → 身份确认 → 会员减免 → 地图切换 → 路线预览。追问继续沿用停车语境。',product:'同一条任务路径连接停车信息、会员权益与出行服务；显示演示时间，避免将余位当作到达保证。',form:'一句结论 + 比较卡片 + 地图',screen:'parking'},food:{n:'02',en:'FIND YOUR KIND OF FLAVOUR',title:'先懂这一餐，\n再推荐这一家。',quote:'“4 个人一起，想吃火锅，有什么划算的？”',ux:'人数与口味是关键约束，用少量选项帮助用户补齐信息，再展示适配套餐。',interaction:'偏好选择 → 套餐卡片 → 优惠券领取 → 详情确认 → 到店路线。已领取状态持续保留。',product:'推荐解释人数匹配与参考价格，避免盲目推销；套餐详情与优惠规则保持独立，减少误解。',form:'澄清问题 + 商品卡 + 优惠券',screen:'food'},events:{n:'03',en:'A WEEKEND WORTH EXPLORING',title:'不用翻遍列表，\n找到想去的那一场。',quote:'“周末有什么活动？想带孩子一起。”',ux:'按日期与兴趣组织信息，用时间顺序帮助比较，不再混用“今天”和“周末”。',interaction:'切换日期 → 兴趣筛选 → 查看详情 → 选择人数 → 确认模拟预约。免费活动直接查看路线。',product:'日历、详情与预约单共享活动信息；购票前显示场次与总价，避免在推荐环节直接下单。',form:'日期切换 + 时间轴 + 确认单',screen:'events'},trip:{n:'04',en:'MAKE ROOM FOR A SLOW AFTERNOON',title:'计划可以完整，\n节奏依然自由。',quote:'“带 6 岁孩子来，半天怎么安排不太累？”',ux:'把同行人与可用时间变成行程依据，主动留出用餐、步行和休息，降低规划负担。',interaction:'澄清条件 → 生成行程 → 局部换一站 → 切换雨天方案 → 保存及导出文本。',product:'从单点推荐扩展到连续到访体验；用户拥有调整权，保存状态仅在本地，不假装已完成真实预约。',form:'多轮对话 + 可调整行程单',screen:'trip'},member:{n:'05',en:'BENEFITS YOU CAN UNDERSTAND',title:'权益不只是说明，\n也是眼前的确定。',quote:'“我是金卡会员，停 5 小时需要付多少？”',ux:'先确认身份，区分总权益与今日剩余额度，用试算把抽象规则变成具体金额。',interaction:'身份选择 → 会员卡 → 费用试算 → 修改停留时长 → 查看停车路线。',product:'说明自动抵扣的前提与估算口径；金卡信息为演示身份，实际项目需接入会员与停车计费系统。',form:'身份确认 + 权益卡 + 费用试算',screen:'member'},service:{n:'06',en:'CARE THAT FOLLOWS THROUGH',title:'认真对待每一次反馈，\n直到问题有了着落。',quote:'“洗手间地面湿滑，带着孩子差点摔倒。”',ux:'回应实际处境，先提示避开湿滑区域；不轻佻安慰，也不以优惠券代替解决问题。',interaction:'描述问题 → 编辑位置与摘要 → 用户确认 → 工单进度 → 结果评价；保留人工入口。',product:'将反馈结构化为可跟进事项，记录未解决分支。原型中的进度明确为模拟，不承诺真实响应时效。',form:'自然语言 + 确认表单 + 状态时间轴',screen:'service'}};
Object.assign(cases,{hotel:{n:'07',en:'STAY A LITTLE LONGER',title:'住得合适，\n才能玩得从容。',quote:'“住一晚，想要江景房，两个人每晚 800 以内。”',ux:'入住日期、人数、预算与偏好先行，推荐同时显示位置、早餐、每晚价和全程总价，帮助比较。',interaction:'入住条件 → 酒店列表 → 房型与退改 → 核对订单 → 勾选确认 → 模拟预订 → 加入行程或取消。',product:'房价与具体日期绑定；先披露退改规则再确认。名称与房源为概念示例，后续需接入酒店库存和订单系统。',form:'条件表单 + 酒店比较卡 + 订单确认',screen:'hotel'},tickets:{n:'08',en:'TURN AN IDEA INTO A TICKET',title:'把“想去看看”，\n变成清楚的出发计划。',quote:'“想坐游船或者看个展，能帮我订票吗？”',ux:'推荐先解释体验差异，再让用户选择日期、场次、票种与数量；亲子票明确人数与适用条件。',interaction:'推荐比较 → 选择日期场次 → 票种与数量 → 总价联动 → 规则确认 → 模拟预订 → 行程关联。',product:'LUI 承担意图理解，GUI 承担精确信息录入；未接入出票和支付时，订单明确标识为模拟凭证。',form:'票务推荐 + 日期场次 + 订单状态',screen:'tickets'}});


document.querySelector('.module-nav').innerHTML=modulePages.map((m,i)=>`<a href="#module-${m.key}"><span>0${i+1}</span>${m.name}</a>`).join('');
document.getElementById('scenario-content').innerHTML=modulePages.map((m,i)=>{const c=cases[m.key];return `<section class="business-module" id="module-${m.key}" aria-labelledby="title-${m.key}"><header class="module-heading"><div><div class="eyebrow">MODULE 0${i+1} / ${c.en}</div><h3 id="title-${m.key}">${m.name}<span>${c.title.replace('\n','')}</span></h3><p class="module-question">${c.quote}</p></div><a class="text-link" href="prototype.html?scene=${m.key}">体验完整对话 <i class="ph ph-arrow-up-right"></i></a></header><div class="module-flow"><span>任务路径</span>${m.path}<small>${c.form}</small></div><div class="module-pages">${m.pages.map((p,n)=>currentPageMarkup(m,p,n)).join('')}</div><div class="module-insights"><article><span>UX / 用户体验</span><p>${c.ux}</p></article><article><span>INTERACTION / 交互设计</span><p>${c.interaction}</p></article><article><span>PRODUCT / 产品体验</span><p>${c.product}</p></article></div></section>`}).join('');
resizeModulePhones();

// Generated module anchors need an explicit initial position after rendering.
if(location.hash.startsWith('#module-'))requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());
